# Generated by Django 5.2.4 on 2025-11-07 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysiologicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BVP_mean", models.FloatField()),
                ("BVP_std", models.FloatField()),
                ("BVP_peak_freq", models.FloatField()),
                ("EDA_phasic_mean", models.FloatField()),
                ("EDA_phasic_min", models.FloatField()),
                ("EDA_smna_min", models.FloatField()),
                ("EDA_tonic_mean", models.FloatField()),
                ("Resp_mean", models.FloatField()),
                ("Resp_std", models.FloatField()),
                ("TEMP_mean", models.FloatField()),
                ("TEMP_std", models.FloatField()),
                ("TEMP_slope", models.FloatField()),
                ("age", models.IntegerField()),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                (
                    "predicted_level",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("confidence_amused", models.FloatField(blank=True, null=True)),
                ("confidence_neutral", models.FloatField(blank=True, null=True)),
                ("confidence_stressed", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
